# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=xyz.coolsa.kaleidoscopes
user=coolsa
slug=kaleidoscopes
modId=kaleidoscopes
modName=Kaleidoscopes
modDescription=Kaleidoscopes! Can be crafted with a spyglass and things.
authors=Coolsa
contributors=Coolsa
license=MPL 2.0
# Mod Version
modVersion=0.2.5
# Branch Metadata
branchName=fabric-1.21.8
compatibleVersions=1.21.8
compatibleLoaders=fabric
